export interface City {
  name: string;
  country: string;
  continent: string;
  population?: number;
  searchTerms: string; // For better search matching
}

export const worldCities: City[] = [
  // North America
  { name: "New York", country: "United States", continent: "North America", population: 8400000, searchTerms: "new york nyc new york city manhattan" },
  { name: "Los Angeles", country: "United States", continent: "North America", population: 4000000, searchTerms: "los angeles la california hollywood" },
  { name: "Chicago", country: "United States", continent: "North America", population: 2700000, searchTerms: "chicago illinois windy city" },
  { name: "Houston", country: "United States", continent: "North America", population: 2300000, searchTerms: "houston texas space city" },
  { name: "Phoenix", country: "United States", continent: "North America", population: 1700000, searchTerms: "phoenix arizona" },
  { name: "Philadelphia", country: "United States", continent: "North America", population: 1600000, searchTerms: "philadelphia philly pennsylvania" },
  { name: "San Antonio", country: "United States", continent: "North America", population: 1500000, searchTerms: "san antonio texas" },
  { name: "San Diego", country: "United States", continent: "North America", population: 1400000, searchTerms: "san diego california" },
  { name: "Dallas", country: "United States", continent: "North America", population: 1300000, searchTerms: "dallas texas big d" },
  { name: "San Jose", country: "United States", continent: "North America", population: 1000000, searchTerms: "san jose california silicon valley" },
  { name: "Austin", country: "United States", continent: "North America", population: 980000, searchTerms: "austin texas music city" },
  { name: "Jacksonville", country: "United States", continent: "North America", population: 900000, searchTerms: "jacksonville florida" },
  { name: "San Francisco", country: "United States", continent: "North America", population: 880000, searchTerms: "san francisco sf california golden gate" },
  { name: "Columbus", country: "United States", continent: "North America", population: 900000, searchTerms: "columbus ohio" },
  { name: "Charlotte", country: "United States", continent: "North America", population: 880000, searchTerms: "charlotte north carolina" },
  { name: "Fort Worth", country: "United States", continent: "North America", population: 920000, searchTerms: "fort worth texas" },
  { name: "Indianapolis", country: "United States", continent: "North America", population: 880000, searchTerms: "indianapolis indiana indy" },
  { name: "Seattle", country: "United States", continent: "North America", population: 750000, searchTerms: "seattle washington emerald city" },
  { name: "Denver", country: "United States", continent: "North America", population: 720000, searchTerms: "denver colorado mile high city" },
  { name: "Boston", country: "United States", continent: "North America", population: 690000, searchTerms: "boston massachusetts beantown" },
  { name: "Nashville", country: "United States", continent: "North America", population: 690000, searchTerms: "nashville tennessee music city" },
  { name: "Baltimore", country: "United States", continent: "North America", population: 600000, searchTerms: "baltimore maryland charm city" },
  { name: "Oklahoma City", country: "United States", continent: "North America", population: 700000, searchTerms: "oklahoma city oklahoma okc" },
  { name: "Louisville", country: "United States", continent: "North America", population: 620000, searchTerms: "louisville kentucky" },
  { name: "Portland", country: "United States", continent: "North America", population: 650000, searchTerms: "portland oregon rose city" },
  { name: "Las Vegas", country: "United States", continent: "North America", population: 640000, searchTerms: "las vegas nevada sin city" },
  { name: "Milwaukee", country: "United States", continent: "North America", population: 590000, searchTerms: "milwaukee wisconsin" },
  { name: "Albuquerque", country: "United States", continent: "North America", population: 560000, searchTerms: "albuquerque new mexico" },
  { name: "Tucson", country: "United States", continent: "North America", population: 550000, searchTerms: "tucson arizona" },
  { name: "Fresno", country: "United States", continent: "North America", population: 540000, searchTerms: "fresno california" },
  { name: "Sacramento", country: "United States", continent: "North America", population: 510000, searchTerms: "sacramento california" },
  { name: "Kansas City", country: "United States", continent: "North America", population: 490000, searchTerms: "kansas city missouri" },
  { name: "Mesa", country: "United States", continent: "North America", population: 510000, searchTerms: "mesa arizona" },
  { name: "Atlanta", country: "United States", continent: "North America", population: 500000, searchTerms: "atlanta georgia hotlanta" },
  { name: "Colorado Springs", country: "United States", continent: "North America", population: 480000, searchTerms: "colorado springs colorado" },
  { name: "Raleigh", country: "United States", continent: "North America", population: 470000, searchTerms: "raleigh north carolina" },
  { name: "Omaha", country: "United States", continent: "North America", population: 470000, searchTerms: "omaha nebraska" },
  { name: "Miami", country: "United States", continent: "North America", population: 460000, searchTerms: "miami florida magic city" },
  { name: "Long Beach", country: "United States", continent: "North America", population: 460000, searchTerms: "long beach california" },
  { name: "Virginia Beach", country: "United States", continent: "North America", population: 450000, searchTerms: "virginia beach virginia" },
  { name: "Oakland", country: "United States", continent: "North America", population: 430000, searchTerms: "oakland california" },
  { name: "Minneapolis", country: "United States", continent: "North America", population: 430000, searchTerms: "minneapolis minnesota twin cities" },
  { name: "Tulsa", country: "United States", continent: "North America", population: 410000, searchTerms: "tulsa oklahoma" },
  { name: "Arlington", country: "United States", continent: "North America", population: 400000, searchTerms: "arlington texas" },
  { name: "Tampa", country: "United States", continent: "North America", population: 390000, searchTerms: "tampa florida" },
  { name: "New Orleans", country: "United States", continent: "North America", population: 390000, searchTerms: "new orleans louisiana big easy nola" },

  // Canada
  { name: "Toronto", country: "Canada", continent: "North America", population: 2930000, searchTerms: "toronto ontario canada" },
  { name: "Montreal", country: "Canada", continent: "North America", population: 1780000, searchTerms: "montreal quebec canada" },
  { name: "Vancouver", country: "Canada", continent: "North America", population: 630000, searchTerms: "vancouver british columbia canada" },
  { name: "Calgary", country: "Canada", continent: "North America", population: 1340000, searchTerms: "calgary alberta canada" },
  { name: "Edmonton", country: "Canada", continent: "North America", population: 970000, searchTerms: "edmonton alberta canada" },
  { name: "Ottawa", country: "Canada", continent: "North America", population: 990000, searchTerms: "ottawa ontario canada capital" },
  { name: "Winnipeg", country: "Canada", continent: "North America", population: 750000, searchTerms: "winnipeg manitoba canada" },
  { name: "Quebec City", country: "Canada", continent: "North America", population: 540000, searchTerms: "quebec city quebec canada" },

  // Mexico
  { name: "Mexico City", country: "Mexico", continent: "North America", population: 9200000, searchTerms: "mexico city cdmx ciudad de mexico" },
  { name: "Guadalajara", country: "Mexico", continent: "North America", population: 1460000, searchTerms: "guadalajara jalisco mexico" },
  { name: "Monterrey", country: "Mexico", continent: "North America", population: 1140000, searchTerms: "monterrey nuevo leon mexico" },
  { name: "Puebla", country: "Mexico", continent: "North America", population: 1530000, searchTerms: "puebla mexico" },
  { name: "Tijuana", country: "Mexico", continent: "North America", population: 1640000, searchTerms: "tijuana baja california mexico" },
  { name: "León", country: "Mexico", continent: "North America", population: 1240000, searchTerms: "leon guanajuato mexico" },
  { name: "Juárez", country: "Mexico", continent: "North America", population: 1320000, searchTerms: "juarez ciudad juarez chihuahua mexico" },
  { name: "Cancún", country: "Mexico", continent: "North America", population: 890000, searchTerms: "cancun quintana roo mexico" },

  // Europe
  { name: "London", country: "United Kingdom", continent: "Europe", population: 9000000, searchTerms: "london england uk britain" },
  { name: "Paris", country: "France", continent: "Europe", population: 2160000, searchTerms: "paris france city of light" },
  { name: "Berlin", country: "Germany", continent: "Europe", population: 3670000, searchTerms: "berlin germany deutschland" },
  { name: "Madrid", country: "Spain", continent: "Europe", population: 3220000, searchTerms: "madrid spain españa" },
  { name: "Rome", country: "Italy", continent: "Europe", population: 2870000, searchTerms: "rome roma italy italia eternal city" },
  { name: "Amsterdam", country: "Netherlands", continent: "Europe", population: 870000, searchTerms: "amsterdam netherlands holland" },
  { name: "Vienna", country: "Austria", continent: "Europe", population: 1900000, searchTerms: "vienna wien austria" },
  { name: "Barcelona", country: "Spain", continent: "Europe", population: 1620000, searchTerms: "barcelona catalonia spain" },
  { name: "Munich", country: "Germany", continent: "Europe", population: 1470000, searchTerms: "munich munchen germany bavaria" },
  { name: "Milan", country: "Italy", continent: "Europe", population: 1370000, searchTerms: "milan milano italy" },
  { name: "Prague", country: "Czech Republic", continent: "Europe", population: 1310000, searchTerms: "prague praha czech republic" },
  { name: "Brussels", country: "Belgium", continent: "Europe", population: 1210000, searchTerms: "brussels bruxelles belgium" },
  { name: "Warsaw", country: "Poland", continent: "Europe", population: 1760000, searchTerms: "warsaw warszawa poland" },
  { name: "Hamburg", country: "Germany", continent: "Europe", population: 1900000, searchTerms: "hamburg germany" },
  { name: "Budapest", country: "Hungary", continent: "Europe", population: 1750000, searchTerms: "budapest hungary" },
  { name: "Stockholm", country: "Sweden", continent: "Europe", population: 970000, searchTerms: "stockholm sweden" },
  { name: "Gothenburg", country: "Sweden", continent: "Europe", population: 580000, searchTerms: "gothenburg goteborg sweden" },
  { name: "Malmö", country: "Sweden", continent: "Europe", population: 350000, searchTerms: "malmo sweden" },
  { name: "Uppsala", country: "Sweden", continent: "Europe", population: 230000, searchTerms: "uppsala sweden" },
  { name: "Copenhagen", country: "Denmark", continent: "Europe", population: 640000, searchTerms: "copenhagen kobenhavn denmark" },
  { name: "Aarhus", country: "Denmark", continent: "Europe", population: 280000, searchTerms: "aarhus denmark" },
  { name: "Odense", country: "Denmark", continent: "Europe", population: 180000, searchTerms: "odense denmark" },
  { name: "Helsinki", country: "Finland", continent: "Europe", population: 650000, searchTerms: "helsinki finland" },
  { name: "Espoo", country: "Finland", continent: "Europe", population: 290000, searchTerms: "espoo finland" },
  { name: "Tampere", country: "Finland", continent: "Europe", population: 240000, searchTerms: "tampere finland" },
  { name: "Vantaa", country: "Finland", continent: "Europe", population: 230000, searchTerms: "vantaa finland" },
  { name: "Turku", country: "Finland", continent: "Europe", population: 190000, searchTerms: "turku finland" },
  { name: "Oulu", country: "Finland", continent: "Europe", population: 210000, searchTerms: "oulu finland" },
  { name: "Lahti", country: "Finland", continent: "Europe", population: 120000, searchTerms: "lahti finland" },
  { name: "Kuopio", country: "Finland", continent: "Europe", population: 120000, searchTerms: "kuopio finland" },
  { name: "Pori", country: "Finland", continent: "Europe", population: 85000, searchTerms: "pori finland" },
  { name: "Jyväskylä", country: "Finland", continent: "Europe", population: 140000, searchTerms: "jyvaskyla finland" },
  { name: "Lappeenranta", country: "Finland", continent: "Europe", population: 73000, searchTerms: "lappeenranta finland" },
  { name: "Rovaniemi", country: "Finland", continent: "Europe", population: 63000, searchTerms: "rovaniemi finland lapland santa claus" },
  { name: "Vaasa", country: "Finland", continent: "Europe", population: 67000, searchTerms: "vaasa finland" },
  { name: "Joensuu", country: "Finland", continent: "Europe", population: 76000, searchTerms: "joensuu finland" },
  { name: "Oslo", country: "Norway", continent: "Europe", population: 690000, searchTerms: "oslo norway" },
  { name: "Bergen", country: "Norway", continent: "Europe", population: 280000, searchTerms: "bergen norway" },
  { name: "Trondheim", country: "Norway", continent: "Europe", population: 210000, searchTerms: "trondheim norway" },
  { name: "Stavanger", country: "Norway", continent: "Europe", population: 140000, searchTerms: "stavanger norway" },
  { name: "Drammen", country: "Norway", continent: "Europe", population: 120000, searchTerms: "drammen norway" },
  { name: "Fredrikstad", country: "Norway", continent: "Europe", population: 80000, searchTerms: "fredrikstad norway" },
  { name: "Kristiansand", country: "Norway", continent: "Europe", population: 110000, searchTerms: "kristiansand norway" },
  { name: "Sandnes", country: "Norway", continent: "Europe", population: 80000, searchTerms: "sandnes norway" },
  { name: "Tromsø", country: "Norway", continent: "Europe", population: 76000, searchTerms: "tromso norway northern lights" },
  { name: "Sarpsborg", country: "Norway", continent: "Europe", population: 56000, searchTerms: "sarpsborg norway" },
  { name: "Zurich", country: "Switzerland", continent: "Europe", population: 420000, searchTerms: "zurich switzerland" },
  { name: "Geneva", country: "Switzerland", continent: "Europe", population: 200000, searchTerms: "geneva geneve switzerland" },
  { name: "Lisbon", country: "Portugal", continent: "Europe", population: 540000, searchTerms: "lisbon lisboa portugal" },
  { name: "Dublin", country: "Ireland", continent: "Europe", population: 560000, searchTerms: "dublin ireland" },
  { name: "Edinburgh", country: "United Kingdom", continent: "Europe", population: 530000, searchTerms: "edinburgh scotland uk" },
  { name: "Manchester", country: "United Kingdom", continent: "Europe", population: 550000, searchTerms: "manchester england uk" },
  { name: "Birmingham", country: "United Kingdom", continent: "Europe", population: 1140000, searchTerms: "birmingham england uk" },
  { name: "Glasgow", country: "United Kingdom", continent: "Europe", population: 630000, searchTerms: "glasgow scotland uk" },
  { name: "Liverpool", country: "United Kingdom", continent: "Europe", population: 500000, searchTerms: "liverpool england uk" },
  { name: "Lyon", country: "France", continent: "Europe", population: 520000, searchTerms: "lyon france" },
  { name: "Marseille", country: "France", continent: "Europe", population: 870000, searchTerms: "marseille france" },
  { name: "Nice", country: "France", continent: "Europe", population: 340000, searchTerms: "nice france cote d'azur" },
  { name: "Naples", country: "Italy", continent: "Europe", population: 960000, searchTerms: "naples napoli italy" },
  { name: "Florence", country: "Italy", continent: "Europe", population: 380000, searchTerms: "florence firenze italy" },
  { name: "Venice", country: "Italy", continent: "Europe", population: 260000, searchTerms: "venice venezia italy" },
  { name: "Cologne", country: "Germany", continent: "Europe", population: 1090000, searchTerms: "cologne koln germany" },
  { name: "Frankfurt", country: "Germany", continent: "Europe", population: 750000, searchTerms: "frankfurt germany main" },
  { name: "Stuttgart", country: "Germany", continent: "Europe", population: 630000, searchTerms: "stuttgart germany" },
  { name: "Düsseldorf", country: "Germany", continent: "Europe", population: 620000, searchTerms: "dusseldorf germany" },
  { name: "Seville", country: "Spain", continent: "Europe", population: 690000, searchTerms: "seville sevilla spain" },
  { name: "Valencia", country: "Spain", continent: "Europe", population: 800000, searchTerms: "valencia spain" },
  { name: "Bilbao", country: "Spain", continent: "Europe", population: 350000, searchTerms: "bilbao spain basque" },

  // Asia
  { name: "Tokyo", country: "Japan", continent: "Asia", population: 14000000, searchTerms: "tokyo japan" },
  { name: "Shanghai", country: "China", continent: "Asia", population: 28000000, searchTerms: "shanghai china" },
  { name: "Beijing", country: "China", continent: "Asia", population: 21500000, searchTerms: "beijing peking china" },
  { name: "Guangzhou", country: "China", continent: "Asia", population: 15000000, searchTerms: "guangzhou canton china" },
  { name: "Shenzhen", country: "China", continent: "Asia", population: 17500000, searchTerms: "shenzhen china" },
  { name: "Mumbai", country: "India", continent: "Asia", population: 20400000, searchTerms: "mumbai bombay india" },
  { name: "Delhi", country: "India", continent: "Asia", population: 32900000, searchTerms: "delhi new delhi india" },
  { name: "Bangalore", country: "India", continent: "Asia", population: 8400000, searchTerms: "bangalore bengaluru india silicon valley" },
  { name: "Hyderabad", country: "India", continent: "Asia", population: 6800000, searchTerms: "hyderabad india" },
  { name: "Chennai", country: "India", continent: "Asia", population: 7100000, searchTerms: "chennai madras india" },
  { name: "Kolkata", country: "India", continent: "Asia", population: 4500000, searchTerms: "kolkata calcutta india" },
  { name: "Pune", country: "India", continent: "Asia", population: 3100000, searchTerms: "pune india" },
  { name: "Ahmedabad", country: "India", continent: "Asia", population: 5600000, searchTerms: "ahmedabad india" },
  { name: "Jaipur", country: "India", continent: "Asia", population: 3100000, searchTerms: "jaipur india pink city" },
  { name: "Seoul", country: "South Korea", continent: "Asia", population: 9700000, searchTerms: "seoul south korea" },
  { name: "Singapore", country: "Singapore", continent: "Asia", population: 5900000, searchTerms: "singapore city state" },
  { name: "Hong Kong", country: "Hong Kong", continent: "Asia", population: 7400000, searchTerms: "hong kong hk" },
  { name: "Osaka", country: "Japan", continent: "Asia", population: 2700000, searchTerms: "osaka japan" },
  { name: "Kyoto", country: "Japan", continent: "Asia", population: 1460000, searchTerms: "kyoto japan" },
  { name: "Yokohama", country: "Japan", continent: "Asia", population: 3750000, searchTerms: "yokohama japan" },
  { name: "Bangkok", country: "Thailand", continent: "Asia", population: 10500000, searchTerms: "bangkok thailand krung thep" },
  { name: "Jakarta", country: "Indonesia", continent: "Asia", population: 10600000, searchTerms: "jakarta indonesia" },
  { name: "Manila", country: "Philippines", continent: "Asia", population: 1800000, searchTerms: "manila philippines" },
  { name: "Kuala Lumpur", country: "Malaysia", continent: "Asia", population: 1800000, searchTerms: "kuala lumpur malaysia kl" },
  { name: "Ho Chi Minh City", country: "Vietnam", continent: "Asia", population: 9000000, searchTerms: "ho chi minh city saigon vietnam" },
  { name: "Hanoi", country: "Vietnam", continent: "Asia", population: 8100000, searchTerms: "hanoi vietnam" },
  { name: "Taipei", country: "Taiwan", continent: "Asia", population: 2600000, searchTerms: "taipei taiwan" },
  { name: "Chongqing", country: "China", continent: "Asia", population: 32000000, searchTerms: "chongqing china" },
  { name: "Tianjin", country: "China", continent: "Asia", population: 15600000, searchTerms: "tianjin china" },
  { name: "Wuhan", country: "China", continent: "Asia", population: 11200000, searchTerms: "wuhan china" },
  { name: "Dongguan", country: "China", continent: "Asia", population: 10650000, searchTerms: "dongguan china" },
  { name: "Foshan", country: "China", continent: "Asia", population: 9500000, searchTerms: "foshan china" },
  { name: "Nanjing", country: "China", continent: "Asia", population: 9300000, searchTerms: "nanjing china" },
  { name: "Shenyang", country: "China", continent: "Asia", population: 9100000, searchTerms: "shenyang china" },
  { name: "Hangzhou", country: "China", continent: "Asia", population: 12200000, searchTerms: "hangzhou china" },
  { name: "Xi'an", country: "China", continent: "Asia", population: 12900000, searchTerms: "xian china" },
  { name: "Harbin", country: "China", continent: "Asia", population: 10600000, searchTerms: "harbin china" },
  { name: "Suzhou", country: "China", continent: "Asia", population: 12800000, searchTerms: "suzhou china" },
  { name: "Qingdao", country: "China", continent: "Asia", population: 10000000, searchTerms: "qingdao china" },
  { name: "Dalian", country: "China", continent: "Asia", population: 7000000, searchTerms: "dalian china" },

  // Middle East
  { name: "Dubai", country: "United Arab Emirates", continent: "Asia", population: 3400000, searchTerms: "dubai uae emirates" },
  { name: "Abu Dhabi", country: "United Arab Emirates", continent: "Asia", population: 1500000, searchTerms: "abu dhabi uae emirates" },
  { name: "Doha", country: "Qatar", continent: "Asia", population: 2400000, searchTerms: "doha qatar" },
  { name: "Kuwait City", country: "Kuwait", continent: "Asia", population: 4100000, searchTerms: "kuwait city kuwait" },
  { name: "Riyadh", country: "Saudi Arabia", continent: "Asia", population: 7600000, searchTerms: "riyadh saudi arabia" },
  { name: "Jeddah", country: "Saudi Arabia", continent: "Asia", population: 4700000, searchTerms: "jeddah saudi arabia" },
  { name: "Tel Aviv", country: "Israel", continent: "Asia", population: 460000, searchTerms: "tel aviv israel" },
  { name: "Jerusalem", country: "Israel", continent: "Asia", population: 970000, searchTerms: "jerusalem israel" },
  { name: "Beirut", country: "Lebanon", continent: "Asia", population: 2200000, searchTerms: "beirut lebanon" },
  { name: "Damascus", country: "Syria", continent: "Asia", population: 2300000, searchTerms: "damascus syria" },
  { name: "Amman", country: "Jordan", continent: "Asia", population: 4000000, searchTerms: "amman jordan" },
  { name: "Baghdad", country: "Iraq", continent: "Asia", population: 7000000, searchTerms: "baghdad iraq" },
  { name: "Tehran", country: "Iran", continent: "Asia", population: 9000000, searchTerms: "tehran iran" },
  { name: "Istanbul", country: "Turkey", continent: "Asia", population: 15500000, searchTerms: "istanbul turkey constantinople" },
  { name: "Ankara", country: "Turkey", continent: "Asia", population: 5600000, searchTerms: "ankara turkey" },
  { name: "Izmir", country: "Turkey", continent: "Asia", population: 4400000, searchTerms: "izmir turkey" },

  // Africa
  { name: "Cairo", country: "Egypt", continent: "Africa", population: 20900000, searchTerms: "cairo egypt" },
  { name: "Lagos", country: "Nigeria", continent: "Africa", population: 15400000, searchTerms: "lagos nigeria" },
  { name: "Kinshasa", country: "Democratic Republic of Congo", continent: "Africa", population: 17000000, searchTerms: "kinshasa congo drc" },
  { name: "Johannesburg", country: "South Africa", continent: "Africa", population: 5600000, searchTerms: "johannesburg south africa joburg" },
  { name: "Cape Town", country: "South Africa", continent: "Africa", population: 4600000, searchTerms: "cape town south africa" },
  { name: "Durban", country: "South Africa", continent: "Africa", population: 3900000, searchTerms: "durban south africa" },
  { name: "Alexandria", country: "Egypt", continent: "Africa", population: 5200000, searchTerms: "alexandria egypt" },
  { name: "Casablanca", country: "Morocco", continent: "Africa", population: 3400000, searchTerms: "casablanca morocco" },
  { name: "Rabat", country: "Morocco", continent: "Africa", population: 580000, searchTerms: "rabat morocco" },
  { name: "Marrakech", country: "Morocco", continent: "Africa", population: 930000, searchTerms: "marrakech marrakesh morocco" },
  { name: "Tunis", country: "Tunisia", continent: "Africa", population: 2300000, searchTerms: "tunis tunisia" },
  { name: "Algiers", country: "Algeria", continent: "Africa", population: 2400000, searchTerms: "algiers algeria" },
  { name: "Accra", country: "Ghana", continent: "Africa", population: 2300000, searchTerms: "accra ghana" },
  { name: "Addis Ababa", country: "Ethiopia", continent: "Africa", population: 3400000, searchTerms: "addis ababa ethiopia" },
  { name: "Nairobi", country: "Kenya", continent: "Africa", population: 4400000, searchTerms: "nairobi kenya" },
  { name: "Dar es Salaam", country: "Tanzania", continent: "Africa", population: 6700000, searchTerms: "dar es salaam tanzania" },
  { name: "Kampala", country: "Uganda", continent: "Africa", population: 1700000, searchTerms: "kampala uganda" },
  { name: "Kigali", country: "Rwanda", continent: "Africa", population: 1100000, searchTerms: "kigali rwanda" },
  { name: "Lusaka", country: "Zambia", continent: "Africa", population: 3100000, searchTerms: "lusaka zambia" },
  { name: "Harare", country: "Zimbabwe", continent: "Africa", population: 1500000, searchTerms: "harare zimbabwe" },
  { name: "Maputo", country: "Mozambique", continent: "Africa", population: 1100000, searchTerms: "maputo mozambique" },
  { name: "Luanda", country: "Angola", continent: "Africa", population: 2800000, searchTerms: "luanda angola" },
  { name: "Abidjan", country: "Côte d'Ivoire", continent: "Africa", population: 4400000, searchTerms: "abidjan ivory coast cote d'ivoire" },
  { name: "Dakar", country: "Senegal", continent: "Africa", population: 1100000, searchTerms: "dakar senegal" },

  // South America
  { name: "São Paulo", country: "Brazil", continent: "South America", population: 22400000, searchTerms: "sao paulo brazil" },
  { name: "Rio de Janeiro", country: "Brazil", continent: "South America", population: 6700000, searchTerms: "rio de janeiro brazil rio" },
  { name: "Brasília", country: "Brazil", continent: "South America", population: 3100000, searchTerms: "brasilia brazil capital" },
  { name: "Salvador", country: "Brazil", continent: "South America", population: 2900000, searchTerms: "salvador brazil bahia" },
  { name: "Fortaleza", country: "Brazil", continent: "South America", population: 2700000, searchTerms: "fortaleza brazil" },
  { name: "Belo Horizonte", country: "Brazil", continent: "South America", population: 2500000, searchTerms: "belo horizonte brazil" },
  { name: "Manaus", country: "Brazil", continent: "South America", population: 2200000, searchTerms: "manaus brazil amazon" },
  { name: "Curitiba", country: "Brazil", continent: "South America", population: 1900000, searchTerms: "curitiba brazil" },
  { name: "Recife", country: "Brazil", continent: "South America", population: 1700000, searchTerms: "recife brazil" },
  { name: "Porto Alegre", country: "Brazil", continent: "South America", population: 1500000, searchTerms: "porto alegre brazil" },
  { name: "Belém", country: "Brazil", continent: "South America", population: 1500000, searchTerms: "belem brazil" },
  { name: "Goiânia", country: "Brazil", continent: "South America", population: 1500000, searchTerms: "goiania brazil" },
  { name: "Guarulhos", country: "Brazil", continent: "South America", population: 1400000, searchTerms: "guarulhos brazil" },
  { name: "Campinas", country: "Brazil", continent: "South America", population: 1200000, searchTerms: "campinas brazil" },
  { name: "São Luís", country: "Brazil", continent: "South America", population: 1100000, searchTerms: "sao luis brazil" },
  { name: "São Gonçalo", country: "Brazil", continent: "South America", population: 1000000, searchTerms: "sao goncalo brazil" },
  { name: "Maceió", country: "Brazil", continent: "South America", population: 1000000, searchTerms: "maceio brazil" },
  { name: "Duque de Caxias", country: "Brazil", continent: "South America", population: 900000, searchTerms: "duque de caxias brazil" },
  { name: "Natal", country: "Brazil", continent: "South America", population: 900000, searchTerms: "natal brazil" },
  { name: "Teresina", country: "Brazil", continent: "South America", population: 900000, searchTerms: "teresina brazil" },
  { name: "São Bernardo do Campo", country: "Brazil", continent: "South America", population: 800000, searchTerms: "sao bernardo do campo brazil" },
  { name: "Nova Iguaçu", country: "Brazil", continent: "South America", population: 800000, searchTerms: "nova iguacu brazil" },
  { name: "João Pessoa", country: "Brazil", continent: "South America", population: 800000, searchTerms: "joao pessoa brazil" },
  { name: "Santo André", country: "Brazil", continent: "South America", population: 700000, searchTerms: "santo andre brazil" },
  { name: "Osasco", country: "Brazil", continent: "South America", population: 700000, searchTerms: "osasco brazil" },
  { name: "Jaboatão dos Guararapes", country: "Brazil", continent: "South America", population: 700000, searchTerms: "jaboatao dos guararapes brazil" },
  { name: "Contagem", country: "Brazil", continent: "South America", population: 700000, searchTerms: "contagem brazil" },
  { name: "São José dos Campos", country: "Brazil", continent: "South America", population: 700000, searchTerms: "sao jose dos campos brazil" },
  { name: "Uberlândia", country: "Brazil", continent: "South America", population: 700000, searchTerms: "uberlandia brazil" },
  { name: "Sorocaba", country: "Brazil", continent: "South America", population: 700000, searchTerms: "sorocaba brazil" },
  { name: "Ribeirão Preto", country: "Brazil", continent: "South America", population: 700000, searchTerms: "ribeirao preto brazil" },
  { name: "Buenos Aires", country: "Argentina", continent: "South America", population: 3100000, searchTerms: "buenos aires argentina" },
  { name: "Córdoba", country: "Argentina", continent: "South America", population: 1400000, searchTerms: "cordoba argentina" },
  { name: "Rosario", country: "Argentina", continent: "South America", population: 1200000, searchTerms: "rosario argentina" },
  { name: "Mendoza", country: "Argentina", continent: "South America", population: 1000000, searchTerms: "mendoza argentina" },
  { name: "La Plata", country: "Argentina", continent: "South America", population: 800000, searchTerms: "la plata argentina" },
  { name: "San Miguel de Tucumán", country: "Argentina", continent: "South America", population: 800000, searchTerms: "tucuman argentina san miguel de tucuman" },
  { name: "Mar del Plata", country: "Argentina", continent: "South America", population: 650000, searchTerms: "mar del plata argentina" },
  { name: "Salta", country: "Argentina", continent: "South America", population: 600000, searchTerms: "salta argentina" },
  { name: "Santa Fe", country: "Argentina", continent: "South America", population: 530000, searchTerms: "santa fe argentina" },
  { name: "San Juan", country: "Argentina", continent: "South America", population: 500000, searchTerms: "san juan argentina" },
  { name: "Santiago", country: "Chile", continent: "South America", population: 7100000, searchTerms: "santiago chile" },
  { name: "Valparaíso", country: "Chile", continent: "South America", population: 300000, searchTerms: "valparaiso chile" },
  { name: "Concepción", country: "Chile", continent: "South America", population: 220000, searchTerms: "concepcion chile" },
  { name: "La Serena", country: "Chile", continent: "South America", population: 220000, searchTerms: "la serena chile" },
  { name: "Antofagasta", country: "Chile", continent: "South America", population: 360000, searchTerms: "antofagasta chile" },
  { name: "Viña del Mar", country: "Chile", continent: "South America", population: 330000, searchTerms: "vina del mar chile" },
  { name: "Bogotá", country: "Colombia", continent: "South America", population: 7200000, searchTerms: "bogota colombia" },
  { name: "Medellín", country: "Colombia", continent: "South America", population: 2500000, searchTerms: "medellin colombia" },
  { name: "Cali", country: "Colombia", continent: "South America", population: 2400000, searchTerms: "cali colombia" },
  { name: "Barranquilla", country: "Colombia", continent: "South America", population: 1200000, searchTerms: "barranquilla colombia" },
  { name: "Cartagena", country: "Colombia", continent: "South America", population: 1000000, searchTerms: "cartagena colombia" },
  { name: "Cúcuta", country: "Colombia", continent: "South America", population: 650000, searchTerms: "cucuta colombia" },
  { name: "Bucaramanga", country: "Colombia", continent: "South America", population: 600000, searchTerms: "bucaramanga colombia" },
  { name: "Pereira", country: "Colombia", continent: "South America", population: 470000, searchTerms: "pereira colombia" },
  { name: "Santa Marta", country: "Colombia", continent: "South America", population: 500000, searchTerms: "santa marta colombia" },
  { name: "Ibagué", country: "Colombia", continent: "South America", population: 530000, searchTerms: "ibague colombia" },
  { name: "Lima", country: "Peru", continent: "South America", population: 10700000, searchTerms: "lima peru" },
  { name: "Arequipa", country: "Peru", continent: "South America", population: 1100000, searchTerms: "arequipa peru" },
  { name: "Trujillo", country: "Peru", continent: "South America", population: 900000, searchTerms: "trujillo peru" },
  { name: "Chiclayo", country: "Peru", continent: "South America", population: 600000, searchTerms: "chiclayo peru" },
  { name: "Piura", country: "Peru", continent: "South America", population: 450000, searchTerms: "piura peru" },
  { name: "Iquitos", country: "Peru", continent: "South America", population: 420000, searchTerms: "iquitos peru" },
  { name: "Cusco", country: "Peru", continent: "South America", population: 430000, searchTerms: "cusco cuzco peru" },
  { name: "Huancayo", country: "Peru", continent: "South America", population: 380000, searchTerms: "huancayo peru" },
  { name: "Chimbote", country: "Peru", continent: "South America", population: 370000, searchTerms: "chimbote peru" },
  { name: "Tacna", country: "Peru", continent: "South America", population: 320000, searchTerms: "tacna peru" },
  { name: "Quito", country: "Ecuador", continent: "South America", population: 2800000, searchTerms: "quito ecuador" },
  { name: "Guayaquil", country: "Ecuador", continent: "South America", population: 2700000, searchTerms: "guayaquil ecuador" },
  { name: "Cuenca", country: "Ecuador", continent: "South America", population: 600000, searchTerms: "cuenca ecuador" },
  { name: "Santo Domingo", country: "Ecuador", continent: "South America", population: 450000, searchTerms: "santo domingo ecuador" },
  { name: "Machala", country: "Ecuador", continent: "South America", population: 280000, searchTerms: "machala ecuador" },
  { name: "Manta", country: "Ecuador", continent: "South America", population: 270000, searchTerms: "manta ecuador" },
  { name: "Portoviejo", country: "Ecuador", continent: "South America", population: 280000, searchTerms: "portoviejo ecuador" },
  { name: "Ambato", country: "Ecuador", continent: "South America", population: 390000, searchTerms: "ambato ecuador" },
  { name: "Riobamba", country: "Ecuador", continent: "South America", population: 260000, searchTerms: "riobamba ecuador" },
  { name: "Loja", country: "Ecuador", continent: "South America", population: 280000, searchTerms: "loja ecuador" },
  { name: "Caracas", country: "Venezuela", continent: "South America", population: 2900000, searchTerms: "caracas venezuela" },
  { name: "Maracaibo", country: "Venezuela", continent: "South America", population: 1600000, searchTerms: "maracaibo venezuela" },
  { name: "Valencia", country: "Venezuela", continent: "South America", population: 1400000, searchTerms: "valencia venezuela" },
  { name: "Barquisimeto", country: "Venezuela", continent: "South America", population: 1200000, searchTerms: "barquisimeto venezuela" },
  { name: "Ciudad Guayana", country: "Venezuela", continent: "South America", population: 900000, searchTerms: "ciudad guayana venezuela" },
  { name: "San Cristóbal", country: "Venezuela", continent: "South America", population: 600000, searchTerms: "san cristobal venezuela" },
  { name: "Maturín", country: "Venezuela", continent: "South America", population: 540000, searchTerms: "maturin venezuela" },
  { name: "Ciudad Bolívar", country: "Venezuela", continent: "South America", population: 420000, searchTerms: "ciudad bolivar venezuela" },
  { name: "Cumana", country: "Venezuela", continent: "South America", population: 400000, searchTerms: "cumana venezuela" },
  { name: "Barcelona", country: "Venezuela", continent: "South America", population: 420000, searchTerms: "barcelona venezuela" },
  { name: "La Paz", country: "Bolivia", continent: "South America", population: 2300000, searchTerms: "la paz bolivia" },
  { name: "Santa Cruz de la Sierra", country: "Bolivia", continent: "South America", population: 1400000, searchTerms: "santa cruz bolivia santa cruz de la sierra" },
  { name: "Cochabamba", country: "Bolivia", continent: "South America", population: 600000, searchTerms: "cochabamba bolivia" },
  { name: "Sucre", country: "Bolivia", continent: "South America", population: 280000, searchTerms: "sucre bolivia" },
  { name: "Tarija", country: "Bolivia", continent: "South America", population: 240000, searchTerms: "tarija bolivia" },
  { name: "Potosí", country: "Bolivia", continent: "South America", population: 190000, searchTerms: "potosi bolivia" },
  { name: "Oruro", country: "Bolivia", continent: "South America", population: 260000, searchTerms: "oruro bolivia" },
  { name: "Trinidad", country: "Bolivia", continent: "South America", population: 130000, searchTerms: "trinidad bolivia" },
  { name: "Cobija", country: "Bolivia", continent: "South America", population: 55000, searchTerms: "cobija bolivia" },
  { name: "Asunción", country: "Paraguay", continent: "South America", population: 3200000, searchTerms: "asuncion paraguay" },
  { name: "Ciudad del Este", country: "Paraguay", continent: "South America", population: 300000, searchTerms: "ciudad del este paraguay" },
  { name: "San Lorenzo", country: "Paraguay", continent: "South America", population: 250000, searchTerms: "san lorenzo paraguay" },
  { name: "Luque", country: "Paraguay", continent: "South America", population: 260000, searchTerms: "luque paraguay" },
  { name: "Capiatá", country: "Paraguay", continent: "South America", population: 240000, searchTerms: "capiata paraguay" },
  { name: "Lambaré", country: "Paraguay", continent: "South America", population: 160000, searchTerms: "lambare paraguay" },
  { name: "Fernando de la Mora", country: "Paraguay", continent: "South America", population: 180000, searchTerms: "fernando de la mora paraguay" },
  { name: "Limpio", country: "Paraguay", continent: "South America", population: 110000, searchTerms: "limpio paraguay" },
  { name: "Ñemby", country: "Paraguay", continent: "South America", population: 100000, searchTerms: "nemby paraguay" },
  { name: "Encarnación", country: "Paraguay", continent: "South America", population: 130000, searchTerms: "encarnacion paraguay" },
  { name: "Montevideo", country: "Uruguay", continent: "South America", population: 1400000, searchTerms: "montevideo uruguay" },
  { name: "Salto", country: "Uruguay", continent: "South America", population: 130000, searchTerms: "salto uruguay" },
  { name: "Paysandú", country: "Uruguay", continent: "South America", population: 76000, searchTerms: "paysandu uruguay" },
  { name: "Las Piedras", country: "Uruguay", continent: "South America", population: 71000, searchTerms: "las piedras uruguay" },
  { name: "Rivera", country: "Uruguay", continent: "South America", population: 65000, searchTerms: "rivera uruguay" },
  { name: "Maldonado", country: "Uruguay", continent: "South America", population: 65000, searchTerms: "maldonado uruguay" },
  { name: "Tacuarembó", country: "Uruguay", continent: "South America", population: 55000, searchTerms: "tacuarembo uruguay" },
  { name: "Melo", country: "Uruguay", continent: "South America", population: 51000, searchTerms: "melo uruguay" },
  { name: "Mercedes", country: "Uruguay", continent: "South America", population: 42000, searchTerms: "mercedes uruguay" },
  { name: "Artigas", country: "Uruguay", continent: "South America", population: 41000, searchTerms: "artigas uruguay" },
  { name: "Georgetown", country: "Guyana", continent: "South America", population: 235000, searchTerms: "georgetown guyana" },
  { name: "Linden", country: "Guyana", continent: "South America", population: 29000, searchTerms: "linden guyana" },
  { name: "New Amsterdam", country: "Guyana", continent: "South America", population: 18000, searchTerms: "new amsterdam guyana" },
  { name: "Anna Regina", country: "Guyana", continent: "South America", population: 12000, searchTerms: "anna regina guyana" },
  { name: "Bartica", country: "Guyana", continent: "South America", population: 11000, searchTerms: "bartica guyana" },
  { name: "Skeldon", country: "Guyana", continent: "South America", population: 5000, searchTerms: "skeldon guyana" },
  { name: "Rosignol", country: "Guyana", continent: "South America", population: 4000, searchTerms: "rosignol guyana" },
  { name: "Mahaica", country: "Guyana", continent: "South America", population: 4500, searchTerms: "mahaica guyana" },
  { name: "Parika", country: "Guyana", continent: "South America", population: 4500, searchTerms: "parika guyana" },
  { name: "Wales", country: "Guyana", continent: "South America", population: 2000, searchTerms: "wales guyana" },
  { name: "Paramaribo", country: "Suriname", continent: "South America", population: 240000, searchTerms: "paramaribo suriname" },
  { name: "Lelydorp", country: "Suriname", continent: "South America", population: 18000, searchTerms: "lelydorp suriname" },
  { name: "Nieuw Nickerie", country: "Suriname", continent: "South America", population: 13000, searchTerms: "nieuw nickerie suriname" },
  { name: "Moengo", country: "Suriname", continent: "South America", population: 7000, searchTerms: "moengo suriname" },
  { name: "Albina", country: "Suriname", continent: "South America", population: 5000, searchTerms: "albina suriname" },
  { name: "Mariënburg", country: "Suriname", continent: "South America", population: 4000, searchTerms: "marienburg suriname" },
  { name: "Groningen", country: "Suriname", continent: "South America", population: 3000, searchTerms: "groningen suriname" },
  { name: "Totness", country: "Suriname", continent: "South America", population: 2000, searchTerms: "totness suriname" },
  { name: "Wageningen", country: "Suriname", continent: "South America", population: 2000, searchTerms: "wageningen suriname" },
  { name: "Cayenne", country: "French Guiana", continent: "South America", population: 61000, searchTerms: "cayenne french guiana" },
  { name: "Saint-Laurent-du-Maroni", country: "French Guiana", continent: "South America", population: 45000, searchTerms: "saint laurent du maroni french guiana" },
  { name: "Kourou", country: "French Guiana", continent: "South America", population: 26000, searchTerms: "kourou french guiana" },
  { name: "Remire-Montjoly", country: "French Guiana", continent: "South America", population: 26000, searchTerms: "remire montjoly french guiana" },
  { name: "Matoury", country: "French Guiana", continent: "South America", population: 33000, searchTerms: "matoury french guiana" },
  { name: "Macouria", country: "French Guiana", continent: "South America", population: 12000, searchTerms: "macouria french guiana" },
  { name: "Mana", country: "French Guiana", continent: "South America", population: 9000, searchTerms: "mana french guiana" },
  { name: "Apatou", country: "French Guiana", continent: "South America", population: 8000, searchTerms: "apatou french guiana" },
  { name: "Grand-Santi", country: "French Guiana", continent: "South America", population: 6000, searchTerms: "grand santi french guiana" },
  { name: "Sinnamary", country: "French Guiana", continent: "South America", population: 3000, searchTerms: "sinnamary french guiana" },

  // Oceania
  { name: "Sydney", country: "Australia", continent: "Oceania", population: 5300000, searchTerms: "sydney australia" },
  { name: "Melbourne", country: "Australia", continent: "Oceania", population: 5200000, searchTerms: "melbourne australia" },
  { name: "Brisbane", country: "Australia", continent: "Oceania", population: 2600000, searchTerms: "brisbane australia" },
  { name: "Perth", country: "Australia", continent: "Oceania", population: 2100000, searchTerms: "perth australia" },
  { name: "Adelaide", country: "Australia", continent: "Oceania", population: 1400000, searchTerms: "adelaide australia" },
  { name: "Gold Coast", country: "Australia", continent: "Oceania", population: 680000, searchTerms: "gold coast australia" },
  { name: "Newcastle", country: "Australia", continent: "Oceania", population: 500000, searchTerms: "newcastle australia" },
  { name: "Canberra", country: "Australia", continent: "Oceania", population: 460000, searchTerms: "canberra australia capital" },
  { name: "Sunshine Coast", country: "Australia", continent: "Oceania", population: 350000, searchTerms: "sunshine coast australia" },
  { name: "Wollongong", country: "Australia", continent: "Oceania", population: 300000, searchTerms: "wollongong australia" },
  { name: "Hobart", country: "Australia", continent: "Oceania", population: 250000, searchTerms: "hobart tasmania australia" },
  { name: "Geelong", country: "Australia", continent: "Oceania", population: 250000, searchTerms: "geelong australia" },
  { name: "Townsville", country: "Australia", continent: "Oceania", population: 180000, searchTerms: "townsville australia" },
  { name: "Cairns", country: "Australia", continent: "Oceania", population: 160000, searchTerms: "cairns australia" },
  { name: "Darwin", country: "Australia", continent: "Oceania", population: 150000, searchTerms: "darwin australia" },
  { name: "Toowoomba", country: "Australia", continent: "Oceania", population: 140000, searchTerms: "toowoomba australia" },
  { name: "Ballarat", country: "Australia", continent: "Oceania", population: 110000, searchTerms: "ballarat australia" },
  { name: "Bendigo", country: "Australia", continent: "Oceania", population: 100000, searchTerms: "bendigo australia" },
  { name: "Albury", country: "Australia", continent: "Oceania", population: 90000, searchTerms: "albury australia" },
  { name: "Launceston", country: "Australia", continent: "Oceania", population: 90000, searchTerms: "launceston tasmania australia" },
  { name: "Auckland", country: "New Zealand", continent: "Oceania", population: 1700000, searchTerms: "auckland new zealand" },
  { name: "Wellington", country: "New Zealand", continent: "Oceania", population: 420000, searchTerms: "wellington new zealand capital" },
  { name: "Christchurch", country: "New Zealand", continent: "Oceania", population: 380000, searchTerms: "christchurch new zealand" },
  { name: "Hamilton", country: "New Zealand", continent: "Oceania", population: 180000, searchTerms: "hamilton new zealand" },
  { name: "Tauranga", country: "New Zealand", continent: "Oceania", population: 160000, searchTerms: "tauranga new zealand" },
  { name: "Napier", country: "New Zealand", continent: "Oceania", population: 130000, searchTerms: "napier new zealand" },
  { name: "Dunedin", country: "New Zealand", continent: "Oceania", population: 130000, searchTerms: "dunedin new zealand" },
  { name: "Palmerston North", country: "New Zealand", continent: "Oceania", population: 90000, searchTerms: "palmerston north new zealand" },
  { name: "Nelson", country: "New Zealand", continent: "Oceania", population: 80000, searchTerms: "nelson new zealand" },
  { name: "Rotorua", country: "New Zealand", continent: "Oceania", population: 80000, searchTerms: "rotorua new zealand" },
  { name: "New Plymouth", country: "New Zealand", continent: "Oceania", population: 80000, searchTerms: "new plymouth new zealand" },
  { name: "Whangarei", country: "New Zealand", continent: "Oceania", population: 90000, searchTerms: "whangarei new zealand" },
  { name: "Invercargill", country: "New Zealand", continent: "Oceania", population: 50000, searchTerms: "invercargill new zealand" },
  { name: "Gisborne", country: "New Zealand", continent: "Oceania", population: 38000, searchTerms: "gisborne new zealand" },
  { name: "Suva", country: "Fiji", continent: "Oceania", population: 180000, searchTerms: "suva fiji" },
  { name: "Nadi", country: "Fiji", continent: "Oceania", population: 42000, searchTerms: "nadi fiji" },
  { name: "Lautoka", country: "Fiji", continent: "Oceania", population: 52000, searchTerms: "lautoka fiji" },
  { name: "Labasa", country: "Fiji", continent: "Oceania", population: 25000, searchTerms: "labasa fiji" },
  { name: "Ba", country: "Fiji", continent: "Oceania", population: 14000, searchTerms: "ba fiji" },
  { name: "Sigatoka", country: "Fiji", continent: "Oceania", population: 10000, searchTerms: "sigatoka fiji" },
  { name: "Tavua", country: "Fiji", continent: "Oceania", population: 2000, searchTerms: "tavua fiji" },
  { name: "Rakiraki", country: "Fiji", continent: "Oceania", population: 5000, searchTerms: "rakiraki fiji" },
  { name: "Levuka", country: "Fiji", continent: "Oceania", population: 1000, searchTerms: "levuka fiji" },
  { name: "Korovou", country: "Fiji", continent: "Oceania", population: 3000, searchTerms: "korovou fiji" }
];

// Search function for cities
export function searchCities(query: string, limit: number = 10): City[] {
  if (!query || query.length < 2) return [];

  const searchTerm = query.toLowerCase().trim();

  const matches = worldCities.filter(city => {
    return (
      city.name.toLowerCase().includes(searchTerm) ||
      city.country.toLowerCase().includes(searchTerm) ||
      city.searchTerms.toLowerCase().includes(searchTerm)
    );
  });

  // Sort by relevance: exact matches first, then by population
  return matches
    .sort((a, b) => {
      const aExact = a.name.toLowerCase().startsWith(searchTerm) ? 1 : 0;
      const bExact = b.name.toLowerCase().startsWith(searchTerm) ? 1 : 0;

      if (aExact !== bExact) return bExact - aExact;

      return (b.population || 0) - (a.population || 0);
    })
    .slice(0, limit);
}

// Get popular cities for initial suggestions
export function getPopularCities(limit: number = 20): City[] {
  return worldCities
    .filter(city => city.population && city.population > 1000000)
    .sort((a, b) => (b.population || 0) - (a.population || 0))
    .slice(0, limit);
}